<a href="https://colab.research.google.com/github/leojklarner/uniqplus-aiml-2022/blob/main/UNIQ%2B_intro_to_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Python

*Authors: Leo Klarner, Jin Xu*

Python is one of the most popular programming languages in current use. If you have ever taken a machine learning course or participated in a data science hackathon, chances are you have already written some Python code. Reasons that Python is so popular include that it:


*   is freely available and installable on virtually any system
*   has an intuitive syntax that emphasises simplicity and readability 
*   has a large user base with many high-quality open-source libraries


By [design](https://en.wikipedia.org/wiki/Zen_of_Python), Python tries to encourage code that is as clear and understandable as possible.
As an example, have a look at the following C++/Python code snippets that count from 0 to 2, multiply each number by 10, and print the results:


```
// C++ script that iterates through the numbers 0, 1 and 2,
// multiplies each of them by 10 and prints the results
#include <iostream>
using namespace std;
int main() {
        int j = 10;
        for (int i = 0; i <= 2; i++) {
          cout << i * j << endl;
        }
    return 0;
}
```

```
# the equivalent script in Python
j = 10
for i in range(3):
  print(i * j)
```


You can already see a couple of the design decisions that make writing and reading Python code much easier than in other languages. One of them is that code segments are simply denoted by indenting lines by multiples of 2 or 4 spaces, in contrast to relying on encapsulating statements such as braces. 
Additionally, variables in Python are dynamically typed, meaning that their data type (e.g. integer, floating point, ...) is determined at run time and we don't have to worry as much about type compatibilities when writing the code.

More abstractly, Python is also very flexible in supporting a range of different programming paradigms (such as procedural, object-oriented and functional programming) that we will have a closer look at later on, making it a versatile general-purpose language.

The cost of this easier and more straight-forward way of coding is that programmes written in Python are usually much slower than their equivalents in more restrictive languages such as C/C++. However, many of the open-source libraries mentioned above allow us to outsource some of the computationally expensive parts of our programme to faster languages, while still being able to write most of our code in Python.


---


## Objective of this course

This course will teach you the basic programming skills that are required for a successful research project in the areas of machine learning and data science. It is split into the following three modules:


1.   We will start with an introduction to fundamental concepts of programming in Python, covering the basic syntax required to write working code. 
2.   We will then look at a range of widely-used libraries that underpin most scientific computing research in Python.
3.   Lastly, we will focus on software engineering best practices that will allow you to produce maintainable and reproducible code that can be used and extended by yourself and others.


As many of you will come into this course with different levels of programming/Python experience, we encourage you to work through it at your own speed. The solutions to all excercises can be found at the bottom of the notebook. Taking the time to understand an exercise and solving it without looking at the solution will be a much more productive and rewarding way to learn that will save you time in the long run.

# 1. Fundamental Python

## Objects in Python

The central concept in Python is that of an *object*. All information in a Python programme is represented as an object or a relation between objects.
Every object is fully described by three properties:


1.   **Identity**: a unique address in computer memory at which an object is stored - an object’s identity never changes once it has been created;
2.   **Type**: a characterisation of the object that determines the operations it supports and the values it can take - like the identity, an object’s type is also unchangeable;
3. **Value**: a collection of data that is stored in the object - depending on its type (mutable vs. immutable), an object's value can either change or stay constant after it is created.

In [ ]:
# everything in Python is an object - even just assigning integers
# results in an object with an automatically determined type   

number_a = 1
number_b = 2
number_c = 1

print(number_a, number_b, number_c)
print(type(number_a), type(number_b), type(number_c))

1 2 1
<class 'int'> <class 'int'> <class 'int'>


In [ ]:
# an object's identity (i.e. its unique address in computer memory)
# can be retrieved with the id() function 

print(id(number_a), id(number_b), id(number_c))

11256064 11256096 11256064


In [ ]:
# variables of immutable types (such as integers) that share 
# the same value may be represented by the same object
# whether two variables point to the same object can be
# checked with the "x is y" command

print(number_a is number_b, number_a is number_c)

False True


In [ ]:
# the operations that a specific type allows
# can be listed with the dir() command

print(dir(number_a))

['__abs__', '__add__', '__and__', '__bool__', '__ceil__', '__class__', '__delattr__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floor__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getnewargs__', '__gt__', '__hash__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__le__', '__lshift__', '__lt__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rrshift__', '__rshift__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__trunc__', '__xor__', 'bit_length', 'conjugate', 'denominator', 'from_bytes', 'imag', 'numerator', 'real', 'to_bytes']


### Exercise 1.1

Define an object of type *float* and find out how to represent it as a ratio of integers.

## Basic data types

We have already seen that Python is able to directly infer the type of an object we create by assigning integer and floating point numbers at runtime. Additional "atomic" data types include strings, booleans and None, showcased below.

In [ ]:
# string types are squences of characters
# that can be provided using both single
# and double quotes

string_1 = 'UNIQ'
string_2 = "+"

print(string_1, string_2)

UNIQ +


In [ ]:
# boolean variables are binary types that we
# can use to capture True/False relationships

bool_1 = True
bool_2 = False

if bool_1:
  print(bool_2)
if not bool_2:
  print(bool_1)

False
True


In [ ]:
# the None type can be used to denote the absence
# of a specific value or type

none_1 = None

print(none_1)

None


### Exercise 1.2

Find out how to convert the following string to 'Uniq+'.

In [ ]:
# adding two string objects together concatenates them

string_3 = string_1 + string_2
print(string_3)

UNIQ+


### Exercise 1.3

Choose one other operation of one of the above data types and code up an example. Feel free to look up what exactly your chosen method does and how it is used.

### Composite data types

"Composite" data types are containers that point to a collection of different objects, including other containers. They include lists, tuples, sets and dictionaries.
In contrast to other languages, composite data types in Python are flexible and may contain a mixture of different data types.

In [ ]:
# we can define lists by simply passing comma-separated collection of objects
# lists can be nested and contain objects that are themselves containers

list_1 = [1, 2, 3]
list_2 = [list_1, 4, 5.0, 'six', list_1]

print(list_1, list_2)

# the number of elements in a list (and all other containers)
# can be retrieved with the len() statement

print("Getting the list lengths:", len(list_1), len(list_2))

# the indices of a list start from 0 and can be 
# retrieved as single elements or so-called slices
# slices denote a range of indices between the 
# first (incl.) and the second (excl.)

print("Retrieving with a single index", list_1[0])
print("Retrieving with a slice", list_1[0:2])

# lists are mutable containers, and can thus be modified in-place 

list_2.append(7)
print("Appending a new value to the list:", list_2)

del list_2[0]
print("Deleting the first element of the list:", list_2)

list_2.remove(7)
print("Removing all 7s from the list", list_2)

# modifying the individual objects also modifies them in the list

list_1[0] = 0

print(list_1, list_2)

[1, 2, 3] [[1, 2, 3], 4, 5.0, 'six', [1, 2, 3]]
Getting the list lengths: 3 5
Retrieving with a single index 1
Retrieving with a slice [1, 2]
Appending a new value to the list: [[1, 2, 3], 4, 5.0, 'six', [1, 2, 3], 7]
Deleting the first element of the list: [4, 5.0, 'six', [1, 2, 3], 7]
Removing all 7s from the list [4, 5.0, 'six', [1, 2, 3]]
[0, 2, 3] [4, 5.0, 'six', [0, 2, 3]]


In [ ]:
# tuples are immutable versions of lists, and can not be modified

tuple_1 = ([1, 2, 3], 4)

print("Tuple:", tuple_1)

# however, if they contain mutable objects, these can be modified
# and are their updated values are shown in the tuple

print("First element of tuple (list type):", tuple_1[0])

tuple_1[0][0] = 0

print("Tuple with modified list element:", tuple_1)

Tuple: ([1, 2, 3], 4)
First element of tuple (list type): [1, 2, 3]
Tuple with modified list element: ([0, 2, 3], 4)


In [ ]:
# sets are (mutable) versions of lists that can only contain immutable elements
# they are analogous to mathematical sets and allow very fast 
# set operations such as intersections and unions

set_1 = {1, 2, 2, 3, 3, 3}
set_2 = {3, 3, 3, 4, 4, 4, 4}
print("Two sets:", set_1, set_2)

print("Membership check", 3 in set_1)
print("Intersection of these sets:", set_1 & set_2)
print("Union of these sets:", set_1 | set_2)

Two sets: {1, 2, 3} {3, 4}
Membership check True
Intersection of these sets: {3}
Union of these sets: {1, 2, 3, 4}


In [ ]:
# dictionaries are Pythons version of key-value pairs
# the key can be different (immutable) types, while
# the values can be objects of any type

dict_1 = {"course": "Into to Python", 1: 1, "list": [1, 2, 3]}

# dictionaries allow efficient retrieval of the 
# information at a specific key and are mutable

print("First element in dictionary:", dict_1["course"])
dict_1["list"] = dict_1["list"] + [4]
print("Modified list object:", dict_1["list"])

# the keys and values of a dictionary can be accessed
# separately or jointly

print("Dictionary keys:", dict_1.keys())
print("Dictionary values:", dict_1.values())
print("Dictionary keys and values:", dict_1.items())

First element in dictionary: Into to Python
Modified list object: [1, 2, 3, 4]
Dictionary keys: dict_keys(['course', 1, 'list'])
Dictionary values: dict_values(['Into to Python', 1, [1, 2, 3, 4]])
Dictionary keys and values: dict_items([('course', 'Into to Python'), (1, 1), ('list', [1, 2, 3, 4])])


### Exercise 1.4

Code up one or more examples in which you use each of the composite data types introduced above. Explore at least one operation for every data type that we have not covered so far. Do they work as expected?

### Beware of "copying" mutable types

In [ ]:
# keep in mind that the following operation only creates
# a new pointer to the same dictionary object

dict_2 = dict_1

print("We just create a new pointer to same object:", dict_1 is dict_2)

# changing dict_2 will this also change dict_1

dict_2["changed"] = True

print(dict_1, dict_2)

We just create a new pointer to same object: True
{'course': 'Into to Python', 1: 1, 'list': [1, 2, 3, 4], 'changed': True} {'course': 'Into to Python', 1: 1, 'list': [1, 2, 3, 4], 'changed': True}


In [ ]:
# to truly copy an object and create a separate instance
# python provides the copy library
from copy import copy, deepcopy

# the copy command copies the specific object
copy_1 = copy(dict_1)
print(copy_1 is dict_1, copy_1['list'] is dict_1['list'])

# while the deepcopy command also copies all contained objects
copy_2 = deepcopy(dict_1)
print(copy_2 is dict_1, copy_2['list'] is dict_1['list'])

False True
False False


### Type conversions

Python is very flexible when it comes to converting objects between different types. If the current type of an object is compatible with the new one, you can simply convert it with e.g. the list() command.

In [ ]:
# a non-exhaustive list object type conversions include

print("Int to float:", 1, "->", float(1))
print("Int to bool:", 0, "->", bool(0))
# composite types are always 'True' if they are non-empty
print("Empty list to bool:", [], "->", bool([]))
print("Non-empty list to bool:", list_1, "->", bool(list_1))
print("List to set:", list_1, "->", set(list_1))

# using type conversions on a dictionary operates on it's keys by default
print("Dict keys to list:", dict_1, "->", list(dict_1))
print("Dict values to list:", dict_1, "->", list(dict_1.values()))

Int to float: 1 -> 1.0
Int to bool: 0 -> False
Empty list to bool: [] -> False
Non-empty list to bool: [0, 2, 3] -> True
List to set: [0, 2, 3] -> {0, 2, 3}
Dict keys to list: {'course': 'Into to Python', 1: 1, 'list': [1, 2, 3, 4], 'changed': True} -> ['course', 1, 'list', 'changed']
Dict values to list: {'course': 'Into to Python', 1: 1, 'list': [1, 2, 3, 4], 'changed': True} -> ['Into to Python', 1, [1, 2, 3, 4], True]


### Exercise 1.5

Find at least one type conversion that does not work. Can you think of a non-standard way to make it work?

## Control flow statements

Control flow statements allow us to specify how often and under what conditions certain parts of our programme should be executed. The standard control flow statements in python closely mirror other languages.

In [ ]:
# if statements check whether a given condition is True,
# and execute the operations they contain if it is

if list_1:
    print(list_1)
    
# if statements can be extended by zero or more
# elif (short for else if) statements, that can
# encode additional conditions and avoid excessive
# nesting, and an optional else statement, which
# is executed if all of the specified conditions fail

if 4 in set_1:
    print(set_2)
elif 5 in set_1:
    print(set_2)
else:
    print(set_1)

[0, 2, 3]
{1, 2, 3}


In [ ]:
# in contrast to other langauges like C, python's for statement
# iterates over the items of any container object in the order
# they appear in the sequence

for element in list_1:
    print(element)
    
# when iterating over the elements, they can be processed
# without affecting the underlying container
# however you should usually refrain from modifying the
# container itself, as that usually leads to messy code

for element in list_1:
    element = element * 5 + 1
print(list_1)

# for iterating over a range of integers, python
# provides the range() statement

for i in range(len(list_1)):
    print(list_1[i])

0
2
3
[0, 2, 3]
0
2
3


In [ ]:
# the while loop executes some code block 
# as long as it's condition stays true

while list_1:
    print(list_1)
    list_1.pop()  # this removes the last element in list

[0, 2, 3]
[0, 2]
[0]


### Exercise 1.6

Explore how these control flow statements interact with the operations you discovered in exercise 1.4 and the type conversions (especially to bool) we worked with in exercise 1.5.

## Container comprehensions

Comprehensions are very useful approaches to combine control flow statements that involve containers with a function that acts on each individual element.

In [ ]:
# list comprehensions produce a list from some other iterable type

list_compr_1 = [i for i in range(5)]
list_compr_2 = [2 * i for i in range(5)]

print(list_compr_1)
print(list_compr_2)

# We can also use list comprehensions to perform the equivalent 
# of a filter operation, by putting the filter condition at the end

list_compr_3 = [2 * i for i in range(5) if i % 2 == 0]
print(list_compr_3)

# the same structure exists for dictionaries and sets

set_compr_1 = {2 * i for i in range(5)}
dict_compr_1 = {i: 2 * i for i in range(5)}

print(set_compr_1)
print(dict_compr_1)

# tuples don't have list comprehensions, as they are not mutable,
# however a comprehension that uses (i for i in range(5)) exists
# and is used to define a "generator", not covered in more detail here

[0, 1, 2, 3, 4]
[0, 2, 4, 6, 8]
[0, 4, 8]
{0, 2, 4, 6, 8}
{0: 0, 1: 2, 2: 4, 3: 6, 4: 8}


### Exercise 1.7

Restate your results from exercise 1.6 as a comprehension. Does that make your code more readable? Can you think of examples for which a comprehension does not make sense and the "rolled-out" form is preferable?

## Procedural programming 

So far we've been writing our code as one continuous statement, using for and while loops to repeat parts of it.
However, as our programme gets longer and needs more flexibility, we would like to abstract and compartmentalise certain functionalities, hiding the complexity of the actual processing.
Procedural programming is one of the paradigms that aims to achieve this, based around the idea that code should be structured into a set of re-usable blocks (i.e. procedures).
Each procedure receives some inputs, performs some computation and returns some output. We can then use them to write more complex and readable code, without concerning oruselves with exactly how the computation is performed. 

In Python, these procedures are called functions and we have already used a lot of built-in ones, allowing us to do exactly what they were designed for: performing abstract manipulations without having to worry about how they are implemented.

However, as our programmes get more tailored and complex, we would like to define and compose our own functions. The keyword to do so is def, followed by a list of arguments in parentheses and a return statement. If no return statement is specified, the function will return None by default.
To call a function we use it's name, followed by brackets containing any arguments that we wish to pass. All functions in Python return a single value as their result, although that value can be a container.

In [ ]:
# example of the syntax required to degine a function

def add_one(value):
    return value + 1

print(add_one(1))

2


### Exercise 1.8

Write a short function called wrap that takes two string arguments and returns a new string that has one of these strings at the beginning and end of the original. Meaning that wrap("UNIQ", "+") should produce "+UNIQ+".

### Exercise 1.9

Restate your results from exercises 1.6/1.7 in the form of a function, adding some complexity if you want.

It’s useful to note that even though variables defined inside a function may use the same name as variables defined outside, they don’t refer to the same thing. This is because of variable scoping.

Within a function, any variables that are created (such as those passed as arguments and those newly defined within the function body), only exist within the scope of the function.

In [ ]:
# for example, the f and k variables defined and used within the function 
# do not interfere with those defined outside of the function
# This is useful, since it means we don’t have to worry about conflicts
# of variable names that are defined outside of our function that may cause 
# incorrect behaviour and other issues

f = 0
k = 0

def multiply_by_10(f):
    k = f * 10
    return k

multiply_by_10(2)
multiply_by_10(8)

print(k)

0


## Object-oriented programming

Object-oriented programming is similar to procedural programming in that it aims to build abstract and re-usable code around data. However, we shift our focus from the process of computation to the data with which the computation is performed. The overarching idea is that code should be structured such that all data related to the same object is stored together. This is easiest to understand when thinking about a real-world object, but it is also applicable to more abstract concepts.

We have already worked with objects a lot, as everything in Python (including functions) is represented as an object of a specific type.
Similarly to functions, we can extend the range of built-in objects we have access to by defining our own type. In Python, this is done by defining a custom class, which is a template describing the structure of some collection of data, along with the operations needed to process it.

In [ ]:
class Lecturer:
    
    # almost every class needs an __init__ method
    # which initialises the object with any
    # associated data
    def __init__(self, name):
        self.name = name
        self.rating = None

    # to extend the behaviour of a class beyond data storage
    # we can define our own operations
    # these are defined just as as normal functions, but have to
    # receive the self argument to get access to variables
    # and other methods of the class they are associated with
    def assign_rating(self, rating):
        self.rating = str(rating) + " / 10"
        print("Assigned rating to", self.name, " - ", self.rating)

jin = Lecturer(name="Jin")

print(type(jin))
print(dir(jin))

jin.assign_rating(11)

<class '__main__.Lecturer'>
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'assign_rating', 'name', 'rating']
Assigned rating to Jin  -  11 / 10


The \__init__ method we just used is one of a few special method names which Python will recognise and use to provide a few common behaviours. They are denoted by double underscores and you will have already seen them when examining the built-in classes using the dir() function. A couple of other useful methods include:

* \__str__ - converts an object into its string representation, used when you do str(object) or print(object)
* \__getitem__ - Accesses an object by key, this is how list[x] and dict[x] are implemented
* \__len__ - gets the length of an object - usually the number of items it contains

### Exercise 1.10

Implement a custom class for an object that makes use of all the special methods listed above. Feel free to build it around your results from exercises 1.6/1.7/1.9.

# 2. Working with NumPy

As all data in Python is implemented in the form of objects, numerical operations can be (and almost always are) computationally inefficient. However, similarly to defining functions and objects in pure Python, we can also build functions and objects that interface with faster, lower-level languages like C/C++.

One widely-used library that provides an extensive set of pre-built functionalities for scientific computing is numpy.
It is included in many Python distributions (such as the Colab environment) by default and is the library of choice when working with multi-dimensional arrays (i.e. vectors, matrices and tensors).

Most modern machine learning libraries are either built on numpy (scipy, scikit-learn, ...) or mimic it's syntax (Pytorch, JAX, ...), which means that it is very helpful to have some degree of fluency in it.

In [ ]:
# as we've seen before with the copy library
# we load additional libraries with the 
# import statement and also assign it the alias of "np"
import numpy as np

In [ ]:
# numpy is centred around so-called array objects
# they represent multidimensional vectors/matrices/tensors
# and, superficially, behave similarly to lists.
# However you usually can't (efficiently) change the
# size of the array or the data type of it's elements

vector_1 = np.array([1, 2, 3], dtype=int)
vector_2 = np.array([4, 5, 6], dtype=int)

print(vector_1, vector_2)

# nested lists (i.e. lists of lists) are used to denote multidimensional arrays
# these have to be regular, i.e every row needs to have equally many columns
# and vice versa, as numpy relies on this regularity to speed up oprations

matrix_1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=int)
matrix_2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]], dtype=int)

print(matrix_1)
print(matrix_2)

# the shape of numpy arrays can be accessed through the .shape attribute

print(vector_1.shape, matrix_1.shape)

[1 2 3] [4 5 6]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
(3,) (3, 3)


### Exercise 2.1

Can you reformulate any of your containers from the previous exercises as a numpy array? If not, why is that and how could you extend them so that they are?

One of the main advantages of numpy is that is able to convert relatively slow for-loop type operations in Python into a vectorised version that is executed in a lower-level language.
These vectorized commands are
heavily optimized but still very flexible.
Commonly used commans include. 

In [ ]:
# element-wise addition, subtraction, multiplication and division

print("Element-wise addition:", vector_1 + vector_2)
print("Element-wise subtraction:", vector_1 - vector_2)
print("Element-wise multiplicaton:", vector_1 * vector_2)
print("Element-wise division:", vector_1 / vector_2)

# matrix-matrix/matrix-vector multiplication
# which is only valid if the dimensions align

print(matrix_1 @ matrix_2)
print(matrix_1 @ vector_1)

# finding the the maximum of a matrix along a specific
# dimension (0 = arcross rows, 1 = across columns)

print("Maximum in each column (across rows)", matrix_1.max(0))
print("Maximum in each row (across columns)", matrix_1.max(1))

# finding the mean and standard deviation along a specific dimension
print("Mean of each column", matrix_1.mean(0))
print("Standard deviation of each column", matrix_1.std(0))

# calculating the sum along a specific dimension
print("Sum of each column (across rows)", matrix_1.sum(0))
print("Sum of each row (across columns)", matrix_1.sum(1))
print("Sum of the entire array:", matrix_1.sum())

Element-wise addition: [5 7 9]
Element-wise subtraction: [-3 -3 -3]
Element-wise multiplicaton: [ 4 10 18]
Element-wise division: [0.25 0.4  0.5 ]
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
[14 32 50]
Maximum in each column (across rows) [7 8 9]
Maximum in each row (across columns) [3 6 9]
Mean of each column [4. 5. 6.]
Standard deviation of each column [2.44948974 2.44948974 2.44948974]
Sum of each column (across rows) [12 15 18]
Sum of each row (across columns) [ 6 15 24]
Sum of the entire array: 45


Another important and very useful concept when working with numpy arrays and vectorised functions is broadcasting. This describes how numpy functions treat arrays with different dimensionalities. Subject to certain constraints, a smaller array can be “broadcast” across a larger one so that they have compatible shapes. This makes sure that this loop occurs in C instead of Python, avoiding making needless copies of data and resutling in more efficient algorithms. 

In [ ]:
# as we have seen before, element-wise operations between arrays 
# of matching shapes will pair up corresponding elements

print(vector_1 * vector_2)

# however, if the arrays have different sizes and
# the dimensionality of the larger array is a multiple
# of the dimensionality of the smaller array
# numpy can still carry out element-wise operations
# by "repeating" the smaller array a set number of times
# this is simple to understand for a scalar

vector_3 = np.array([2])
print(vector_1 * vector_3)

# but also works for higher-dimensional arrays, e.g. we can
# element-wise multiply a 1x3 row vector with a 3x3 matrix
# which results in the vector being element-wise multiplied
# with each row of the matrix

print(matrix_1 * vector_1)

[ 4 10 18]
[2 4 6]
[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


### Exercise 2.2

Can you reformulate any of your functions from the previous section as a combination of vectorised numpy functions? If not, why is that and how could you extend either the functions or the underlying data so that they are?

### Exercise 2.3 - data standardisation

In many machine learning applications, we are working with a matrix of N observations, each of wich has D different measured values (often called features, e.g. the height, weight and age of a person).
As each of these features is usually measured on a different scale, a common pre-processing step is to standardise them.

When looking at the data as an NxD matrix, this is achieved by rescaling each of the columns so that they have a mean of zero and a standard deviation of one, which is achieved by the following element-wise operations:



1.   subtract the mean of a specific column from all values in that same column 
2.   divide the values in a specific column by the standard deviation of that same column

Write a function that accepts an NxD data matrix as input and outputs the matrix after normalization. Try to write this function using only vectorised numpy commands.

In [ ]:
# for the sake of this exercise we can start with using a matrix 
# that is filled with randomly generated values through numpy's
# random.rand function, that draws from a uniform distribution between [0, 1]
num_samples, num_features = 200, 10
random_data = np.random.rand(num_samples, num_features)

print(random_data.shape)
print(random_data.mean(0))
print(random_data.std(0))

(200, 10)
[0.49382086 0.50528881 0.53416996 0.48819435 0.49333588 0.51891049
 0.50839676 0.47127583 0.50340598 0.49037545]
[0.29165069 0.27825223 0.30115531 0.27258752 0.27502915 0.2905764
 0.30293345 0.28330029 0.28938878 0.30117487]


In [ ]:
# write a vectorised numpy function to normalise this array
# to a mean of zero and a standard deviation of one in
# each feature dimension (i.e. taking the mean across all data points)



### Exercise 2.4 - Monte Carlo integration

Another nice example to get familiar with numpy is [Monte Carlo integration](https://en.wikipedia.org/wiki/Monte_Carlo_integration). Specifically, we will try to approximate the area of a 2D unit circle ($r=1\rightarrow A=\pi r^2=\pi$) by:



1.   randomly sampling points in the square that encloses the unit circle (i.e. $x\in[-1 ,1], y\in[-1, 1]$) using numpy's [uniform random sampler](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html) seen in the last exercise
2.   calculating the ratio of sampled points that lie within the unit circle ($x^2+y^2\leq 1$)
3.  using that ratio to derive an estimate of $A$

Additional numpy functions that could prove usefule are the [np.where function](https://numpy.org/doc/stable/reference/generated/numpy.where.html) for element-wise comparisons and the [np.power function](https://numpy.org/doc/stable/reference/generated/numpy.power.html) for taking exponents.

# Solutions

 ### Solution 1.1

In [ ]:
# an object of type float is defined by assigning
# a floating point number to a variable

float_1 = 2.5
print(type(float_1))

<class 'float'>


In [ ]:
# the operations that a float object supports
# can be listed with the dir() command

print(dir(float_1))

['__abs__', '__add__', '__bool__', '__ceil__', '__class__', '__delattr__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floor__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getformat__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__int__', '__le__', '__lt__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__pos__', '__pow__', '__radd__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmod__', '__rmul__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__setattr__', '__setformat__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__trunc__', 'as_integer_ratio', 'conjugate', 'fromhex', 'hex', 'imag', 'is_integer', 'real']


In [ ]:
# we find that the object supports an operation
# called 'as_integer_ratio', which displays the
# floating point number as a ratio of integers

print(float_1.as_integer_ratio())

(5, 2)


### Solution 1.2

In [ ]:
# looking at the operations supported by the string type
# we find the capitalize() function, that converts all
# characters to lower case except for the first letter

print(dir(string_3))
print(string_3.capitalize())

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']
Uniq+


### Solution 1.8


In [ ]:
def wrap(a, b):
    return b + a + b

print(wrap("UNIQ", "+"))

+UNIQ+


### Solution 2.3

In [ ]:
def standardise(X):
    X_centered = X - X.mean(0)
    X_standardised = X_centered / X.std(0)
    return X_standardised

In [ ]:
data_standardised = standardise(random_data)
print('means: ', np.mean(data_standardised, axis=0))
print('sd: ', np.std(data_standardised, axis=0))

means:  [ 4.34097203e-16 -2.88102875e-16  4.38538095e-16 -2.50910404e-16
 -2.63122857e-16  1.45716772e-16 -8.17124146e-16 -1.62758695e-15
 -3.79141163e-16  1.04638520e-15]
sd:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### Solution 2.4

In [ ]:
def circle_approx(n_samples):
  samples = np.random.rand(n_samples, 2)
  samples = (samples - 0.5) * 2
  radius = np.power(samples, 2).sum(1)
  ratios = np.where(radius >= 1, False, True)
  return ratios.mean() * 4
circle_approx(100000)

3.14676

### Exercise 2.5 - more advanced for anyone who finishes early

A subtask of many machine learning algorithms is to compute the likelihood $p(\mathbf{x}|\theta)$ of a sample $\mathbf{x}$ given a probability density model with parameters $\theta$. Given two models with $\theta_0$ and $\theta_1$, we would like to find out which model produces the better fit.

For this exercise, we will consider multivariate Normal distributions in $d=5$ dimensions.

$p(\mathbf{x} \mid \boldsymbol{\mu}, \boldsymbol{\Sigma})=\frac{1}{(2 \pi)^{d / 2}|\boldsymbol{\Sigma}|^{1 / 2}} \exp \left(-\frac{1}{2}(\mathbf{x}-\boldsymbol{\mu})^{\top} \boldsymbol{\Sigma}^{-1}(\mathbf{x}-\boldsymbol{\mu})\right)$

where $|\boldsymbol{\Sigma}|$ is the determinant of $\boldsymbol{\Sigma}$ and $\boldsymbol{\Sigma}^{-1}$ it's inverse.

Write a function that 

In [ ]:
# let's again start with a uniform distribution of data points
X = np.random.rand(200, 5)

# set up the two multivariate normal distributions, differing only in their means 
# (uniformly drawn in [0.5, 1] and [0, 0.5] in each dimension)
means = [np.random.rand(X.shape[1]) * 0.5 + 0.5 , - np.random.rand(X.shape[1])  * 0.5 + 0.5]

# and with diagonal covariance matrices
sigmas = [np.diag(np.random.rand(X.shape[1])), np.diag(np.random.rand(X.shape[1]))]

print([m.shape for m in means])
print([s.shape for s in sigmas])

[(5,), (5,)]
[(5, 5), (5, 5)]


In [ ]:
def compute_density(X, mean, sigma):
    
    # compute normalising factor
    factor = 1 / (np.power((2*np.pi), X.shape[1]/2) * np.sqrt(np.linalg.det(sigma)))
    
    # calculate difference to mean and invert sigma
    mean_diff = X - mean
    sigma_inv = np.linalg.inv(sigma)
    
    # compute the densities
    p = factor * np.exp(-0.5 * np.sum(np.multiply(np.matmul(mean_diff, sigma_inv), mean_diff), axis=1))
    return p 

In [ ]:
densities = np.array(
    [compute_density(X, mean, sigma) for mean, sigma in zip(means, sigmas)]
)
densities.argmax(0)

array([1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 0], dtype=int64)